### ISSUE TITLE
Doesn't work on gvim 7.4?

### ISSUE THREAD

**Issue by FabHan** [PProvost/vim-ps1#16]
I'm using Windows 10 and gvim 7.4.

I put `vim-ps1` in `~\.vim\plugin` but starting gvim doesn't seem to load the ps1 script correctly.

I also tried manually: `:source ~\.vim\plugin\vim-ps1\ftplugin\ps1.vim`. Still don't see Powershell among the languages.

**Comment by chantisnake** [comment]
me too

**Comment by jlevitt** [comment]
Same here. I used Vundle to install.

**Comment by chantisnake** [comment]
I figured out the problem, just stick this into your vimrc:
```vim
" enable powershell syntax plug
autocmd BufNewFile,BufReadPost *.ps1 set filetype=ps1
```

then everything works

**Comment by jlevitt** [comment]
@chantisnake that fixed it for me as well. Thanks for posting!

**Comment by dragon788** [comment]
You may also want to add *.psc1 *.psd1 *.psm1 to that list so the various other PowerShell files get the correct syntax highlighting as well.

**Comment by heaths** [comment]
Closing since this seems to be a non-issue now.

**Comment by heaths** [comment]
Actually, I just realized too that if you're on Windows, you don't use "~\.vim" but "~\vimfiles". From `:help runtimepath`:

```
					PC, OS/2: "$HOME/vimfiles,
						$VIM/vimfiles,
						$VIMRUNTIME,
						$VIM/vimfiles/after,
						$HOME/vimfiles/after"
```

Does it work for you if you rename ".vim" to "vimfiles"?

**Comment by heaths** [comment]
Not sure why I reopened this when I commented. Re-closing.
