### ISSUE TITLE
FileType detection not working with Vim 8.0

### ISSUE THREAD

**Issue by pcgeek86** [PProvost/vim-ps1#21]
I've got an Ubuntu 16.04 Xenial Xerus VM with Vim 8.0 installed. I'm using Vundle to install the plug-in, but it's not automatically detecting the filetype for a `.ps1` file. Any ideas what's wrong? 

Seems similar to #16. 

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by heaths** [comment]
It's working with VIM 8.0 when I use pathogen, but I'm not familiar with vundle (apart from knowing it's an alternative for bundles). Can you dump your file system tree that is the root of the various ps1 syntax support files? I can look into it further.

**Comment by pcgeek86** [comment]
@heaths Thanks for being willing to take a look. What's the best way to get this over to you?

FYI Vundle just automatically installs plugins under `~/.vim/bundle/<plugin-name>`. More or less, same idea as Pathogen.

**Comment by heaths** [comment]
I was just thinking a "tree /f" (well, in Windows - may vary on Linux), but what you told me should be good enough. Unfortunately, it also doesn't help since I have the same thing, though "vimfiles" instead of ".vim" (as appropriate on Windows, of course).

Would you be willing to share the log file from `vim -V11log`? There could be personal information in there, so you could search for `ps1.*ftdetect` and paste only those matches + a few additional lines after the match here.

Or if you can duplicate this in a docker image you could paste a Dockerfile or something.

**Comment by pcgeek86** [comment]
> Or if you can duplicate this in a docker image you could paste a Dockerfile or something.

That's a good idea; it'll take me a little time to reproduce. Let me get back to you.

**Comment by heaths** [comment]
FWIW, I tried to repro this in an _unbuntu:trusty_-based container with VIM 8.0 and Vundle and haven't reprod the issue (I believe there's a problem, just not sure what yet). I noticed in the log (`-V11log`) I created that it was looking for various file patterns including anything in the runtime path that matched, among other patterns, _ftdetect.ps1_. Do you see that on your system when you create a log? Per instruction in the _README.md_ file on the Vundle page, did you update your `runtimepath`? (I supposed you'd have to in order to even get Vundle working - just grabbing at straws right now.)

**Comment by pcgeek86** [comment]
Creating a log is a good idea. Which container image did you use BTW?

**Comment by heaths** [comment]
_ubuntu:trusty_, which is currently 16.04. After that, I had a _Dockerfile_ to get all the stuff to install vim 8.0. I'd paste it, but there's one problem I haven't yet worked out (I ended up doing it manually at first, but wanted to write a Dockerfile instead to share out and having problems with the multiline, heredoc-like syntax working - not even sure if it's actually supported since I can't find anything on docker.com abot it).

**Comment by pcgeek86** [comment]
Maybe you could use a command line GitHub Gist tool, like this one, to avoid the need to embed multi-line files in the `Dockerfile`.

https://github.com/defunkt/gist

**Comment by pcgeek86** [comment]
By the way, I'm pretty sure Ubuntu 16.04 is Xenial Xerus.

**Comment by heaths** [comment]
`ubuntu:trusty` is the Docker image tag for 16.04 currently.

I've not been able to repro the issue with this Dockerfile:

```dockerfile
FROM ubuntu:trusty

RUN DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y software-properties-common && \
    apt-get update && \
    add-apt-repository ppa:jonathonf/vim && \
    apt-get install -y \
        vim \
        git

RUN git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim && \
    echo "set nocompatible" > ~/.vimrc && \
    echo "filetype off" >> ~/.vimrc && \
    echo >> ~/.vimrc && \
    echo "set rtp+=~/.vim/bundle/Vundle.vim" >> ~/.vimrc && \
    echo "call vundle#begin()" >> ~/.vimrc && \
    echo >> ~/.vimrc && \
    echo "Plugin 'VundleVim/Vundle.vim'" >> ~/.vimrc && \
    echo "Plugin 'PProvost/vim-ps1'" >> ~/.vimrc && \
    echo >> ~/.vimrc && \
    echo "call vundle#end()" >> ~/.vimrc && \
    echo "filetype plugin indent on" >> ~/.vimrc && \
    echo >> ~/.vimrc && \
    echo "syntax on" >> ~/.vimrc && \
    vim +PluginInstall +qall

ENTRYPOINT ["/bin/bash"]
```

**Comment by pcgeek86** [comment]
That's probably because you didn't do an `apt update` after adding the PPA. 😄 It wasn't installing Vim 8 for me. I fixed it with the following Dockerfile, but I can't replicate the problem with this Docker image either.

```
FROM ubuntu:xenial

RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:jonathonf/vim && \
    apt update && \
    apt-get install -y \
        vim \
        git

RUN git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim && \
    echo "set nocompatible" > ~/.vimrc && \
    echo "filetype off" >> ~/.vimrc && \
    echo >> ~/.vimrc && \
    echo "set rtp+=~/.vim/bundle/Vundle.vim" >> ~/.vimrc && \
    echo "call vundle#begin()" >> ~/.vimrc && \
    echo >> ~/.vimrc && \
    echo "Plugin 'VundleVim/Vundle.vim'" >> ~/.vimrc && \
    echo "Plugin 'PProvost/vim-ps1'" >> ~/.vimrc && \
    echo >> ~/.vimrc && \
    echo "call vundle#end()" >> ~/.vimrc && \
    echo "filetype plugin indent on" >> ~/.vimrc && \
    echo >> ~/.vimrc && \
    echo "syntax on" >> ~/.vimrc && \
    vim +PluginInstall +qall

ENTRYPOINT ["/bin/bash"]
```

I'll close this for now, until I can come up with a consistent repro.

**Comment by pcgeek86** [comment]
I reproduced the problem by copying in my `.vimrc` file. Gonna do some further analysis to see what's up.

**Comment by pcgeek86** [comment]
Can you reproduce it with this `~/.vimrc`? @heaths 

https://gist.github.com/anonymous/70c6c3422879b7d309d95e7e7a13ca84

**Comment by heaths** [comment]
Yes, I can reproduce it but that means one of the other bundles is causing a problem. You can find out which one by turning them off and enabling them one at a time. That doesn't necessarily (and most likely does not) mean there's a problem with this bundle. For example, I have 10 bundles installed using pathogen and this bundle works just fine:

```
Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----        7/28/2016   6:16 PM                vim-fugitive                                                          
d-----        7/28/2016   6:16 PM                vim-git                                                               
d-----        7/28/2016   6:16 PM                vim-markdown                                                          
d-----        7/28/2016   6:16 PM                vim-msbuild                                                           
d-----        7/28/2016   6:16 PM                vim-pathogen                                                          
d-----        7/28/2016   6:16 PM                vim-pipe                                                              
d-----        7/28/2016   6:16 PM                vim-ps1                                                               
d-----        7/28/2016   6:16 PM                vim-repeat                                                            
d-----        7/28/2016   6:16 PM                vim-surround                                                          
d-----        7/28/2016   6:16 PM                vim-typescript                                                        
```

**Comment by pcgeek86** [comment]
Good idea, just wanted to make sure the rest of the configuration looked right. I'll go through them and disable them to find out which is the culprit, and then perhaps submit a PR to fix it.
