### ISSUE TITLE
Add to vim package index (vim-pi)

### ISSUE THREAD

**Issue by jpaugh** [PProvost/vim-ps1#23]
Hello. I added your plugin to the vim package index, so that I could install it automagically via my plugin manager. Please review and provide your input on the [pull request](https://bitbucket.org/vimcommunity/vim-pi/pull-requests/19/new-plugin-vim-ps1-powershell-syntax-etc/diff), over on BitBucket.

Thanks!

**Comment by heaths** [comment]
Looks fine. Thanks.
