### ISSUE TITLE
UTF-8 with BOM is not recommended

### ISSUE THREAD

**Issue by cwegener** [PProvost/vim-ps1#29]
According to the Unicode standard, the BOM for UTF-8 files is not recommended.

https://stackoverflow.com/questions/2223882/whats-different-between-utf-8-and-utf-8-without-bom/2223926#2223926

**Comment by cwegener** [comment]
Can you please reverse PR#26 since the change in PR#26 is unduly impacting vim-ps1 users.
I have provided a solution to the problem reported by @anthony-geoghegan in PR#26.

**Comment by heaths** [comment]
This is not forcing users to use UTF-8. Setting the BOM merely prefixes the script with the BOM of whatever encoding you're using, which provides a directive to the decoder when sniffing would not produce the right results. If you use Unicode for your scripts, placing a BOM would cause no harm. So I fail to see how this is "unduly impacting vim-ps1 users". Can you clarify?

**Comment by cwegener** [comment]
No, it's not forcing UTF-8, but it is instead unconditionally changing every single UTF-8 PS1 file that is being edited to change the encoding from UTF-8 to UTF-8-with-BOM. And UTF-8-with-BOM is not a recommended encoding as per Unicode standard.

**Comment by heaths** [comment]
While it may not be recommended in general, there are cases where it is (or something in its place, like a `ContentType`) or even necessary. I have reached out to the PowerShell team to see what they recommend for scripts. Windows has a long history of ANSI assumptions.

**Comment by cwegener** [comment]
Let me put it another way, why should a syntax highlighting plugin for vim involve itself with file encoding in the first place? I think that file encoding is a choice that each author makes themselves and the file encoding decisions should be separated from syntax highlighting.

**Comment by heaths** [comment]
I heard back from the PowerShell team and they are moving to BOM-less scripts. I will revert the `bomb` change.

**Comment by heaths** [comment]
To your last question, though: these are strictly for syntax highlighting. Quite a few of the ftplugins for various file formats do other things too, like some common compiler options.
