### ISSUE TITLE
Please help me install this plugin

### ISSUE THREAD

**Issue by gitreapur** [PProvost/vim-ps1#34]
Hello,
Can someone please help me get this working?
Windows 10 ent, fully updated
I installed gvim81.exe
I have a _gvimrc file in c:\users\me
I downloaded this plugin vim-ps1-master.zip
I created a directory in c:\users\me\.vim
I unzipped vim-ps1-master.zip in .vim
I also created c:\users\vimfile and unzipped vim-ps1-master.zip into it

When I edit a .ps1 file, I don't see any syntax highlighting. the setting in _gvimrc do work, so I am in the right directory, I think.

What else do I need to do?
Thanks

**Comment by heaths** [comment]
There is a subdirectory in the ZIP from which you need to extract. The "plugins", etc. folders need to be in the root of your ~/.vim (linux) or ~/vimfiles (Windows) directory. Better yet, use pathogen as described in the README of this project.
