### ISSUE TITLE
How do I close the terminal?

### ISSUE THREAD

**Issue by jtpsh** [PProvost/vim-ps1#45]
I recently installed this plugin and everytime I open PS1 files, a terminal buffer is opening as well. This is happening both on my windows10 and Mac. It's not very obvious to me which option i should put. Any thoughts?

**Comment by heaths** [comment]
Can you describe what issue this is causing? Is it visible (I've not seen it)? @Konfekt was this caused by your recent changes?

**Comment by Konfekt** [comment]
Maybe something calls the normal mode mapping `K` that opens a terminal when Vim is run in a GUI. The code I added that coulde cause this was

```vim
" ftplugin/ps1.vim (lines 45-46)
elseif has('terminal')
  command! -buffer -nargs=1 GetHelp silent exe 'term ' . s:pwsh_cmd . ' -NoLogo -NoProfile -NonInteractive -ExecutionPolicy RemoteSigned -Command Get-Help -Full "<args>"' . (executable('less') ? ' | less' : '')
```

I cannot reproduce in Gvim or Vim under Linux though, which should behave similarly to macOS. Does this happen with a minimal `vimrc` such as

```vim
let &rtp = '~/.vim/plugged/vim-ps1' . ',' . &rtp
filetype plugin indent on
syntax on
```

called by ` vim --clean -u ~/.viminrc`?

**Comment by jtpsh** [comment]
I think I found this now - had to disable all my plugins and was able to isolate this with coc-powershell. When I have both plugins on, the integrated PS console shows up every time.

The reason I installed vim-ps1 for the missing syntax highlighting - disabling this plugin seems to disable the intellisense/completion of coc-powershell too. I'll see what fix I can find.
