### ISSUE TITLE
Why is 'formatoptions' j not enabled by default?

### ISSUE THREAD

**Issue by acc987** [PProvost/vim-ps1#53]
Currently ps1.vim overrides the 'formatoptions' as follows:
https://github.com/PProvost/vim-ps1/blob/d0b89c2dc0f6af09d7876963e94e5c7567eacac6/ftplugin/ps1.vim#L16

Unfortunately that means that `set formatoptions+=j` in my .vimrc is not applied for PowerShell files. As that format option seems to work with PowerShell syntax (at least for comments starting with '#', which is what I tried), I wanted to know whether that omission is intentional or accidental?

**Comment by heaths** [comment]
Does that PR look satisfactory?

**Comment by acc987** [comment]
If it's fine with you then merging/accepting the pull request will close this issue for sure.
